# Generated by Django 2.2 on 2019-12-04 16:53

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='Correo electronico')),
                ('tipoem', models.CharField(choices=[('Peticion', 'Peticion'), ('Solicitud', 'Solicitud'), ('Queja', 'Queja'), ('Reclamo', 'Reclamo'), ('Felicitaciones', 'Felicitaciones')], default='Peticion', max_length=50, verbose_name='Categoria')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('msj', ckeditor.fields.RichTextField(default='Quisiera', verbose_name='Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='Empleos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmpNom', models.CharField(max_length=50, verbose_name='Experiencia')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabil', models.CharField(default='Activo', max_length=100, verbose_name='Habilidad')),
                ('NiveHabi', models.CharField(default='Activo', max_length=20, verbose_name='Nivel de Habilidad:')),
            ],
            options={
                'verbose_name': 'Habilidades',
                'verbose_name_plural': 'Habilidades y competencias',
            },
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idUsuario', models.CharField(default='', max_length=50, verbose_name='N. Identificacion')),
                ('ImageUsua', models.ImageField(upload_to='perfiles/img', verbose_name='Foto de Perfil')),
                ('PerfilPro', ckeditor.fields.RichTextField(default='Candidato...', verbose_name='perfil profesional')),
                ('GeneUsua', models.CharField(default='O', max_length=1, verbose_name='Genero')),
                ('TeleUsua', models.CharField(default='0', max_length=20, verbose_name='Telefono')),
                ('CeluUsua', models.CharField(default='0', max_length=20, verbose_name='Celular')),
                ('DireUsua', models.DateTimeField(default='0', verbose_name='Direccion Postal')),
                ('RegisUsua', models.DateTimeField(default=0, verbose_name='Registrado el :')),
                ('EstaUsua', models.CharField(default='Activo', max_length=50, verbose_name='Estado')),
                ('idEstaCivil', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.EstaCivil', verbose_name='Estado Civil')),
                ('idEtnias', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.Etnia', verbose_name='Etnias')),
                ('idTipoDocu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.TipoDocu', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
            },
        ),
        migrations.CreateModel(
            name='Logros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechLogr', models.DateTimeField(default=0, verbose_name='Fecha de Culminacion de logro')),
                ('NomLogr', models.CharField(default='Activo', max_length=100, verbose_name='Logro o Disticion')),
                ('DescLogr', ckeditor.fields.RichTextField(verbose_name='Descripcion o caracteristicas del Logro')),
                ('NombTilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipoLogr', verbose_name='Tipo de logro')),
            ],
            options={
                'verbose_name': 'Logros',
                'verbose_name_plural': 'Logros Obtenidos',
            },
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmprExpe', models.CharField(max_length=150, verbose_name='Empresa')),
                ('TeleEmpr', models.CharField(max_length=30, verbose_name='Telefono de contacto de la empresa')),
                ('JefeExpe', models.CharField(max_length=30, verbose_name='Persona de contacto de la empresa')),
                ('FechIn', models.DateTimeField(default='0', verbose_name='Fecha de inicio')),
                ('FechFin', models.DateTimeField(default='0', verbose_name='Fecha de terminacion')),
                ('FuncionE', ckeditor.fields.RichTextField(verbose_name='Funciones desempeñadas')),
                ('LogrExpe', ckeditor.fields.RichTextField(verbose_name='Logros Alcanzados')),
                ('SopoExpe', models.FileField(default='', upload_to='soportes/laboral', verbose_name='Certificado Laboral')),
                ('EstaExpt', models.CharField(default='Activo', max_length=30, verbose_name='Estado de Experiencia')),
                ('CarExpe', models.ForeignKey(limit_choices_to={'EsCargo': 'SI'}, on_delete=django.db.models.deletion.CASCADE, to='parametros.Empleos', verbose_name='Cargo Ocupado')),
            ],
            options={
                'verbose_name': 'Experiencia',
                'verbose_name_plural': 'Experiencia Laboral',
            },
        ),
        migrations.CreateModel(
            name='Educacions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instituto', models.CharField(default='Activo', max_length=30, verbose_name='Institucion o Academia')),
                ('TituloEst', models.CharField(max_length=250, verbose_name='Titulo Obtenido')),
                ('FechGrado', models.DateTimeField(default=0, verbose_name='Fecha de Graduacion')),
                ('SoporteEs', models.FileField(default='', upload_to='Soporte/educacion', verbose_name='Soporte Educacion')),
                ('EstaEstu', models.CharField(default='Activo', max_length=30, verbose_name='Estado de Educacion')),
                ('TipoEstu', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='parametros.tipoEstu', verbose_name='Tipo de Educacion')),
            ],
            options={
                'verbose_name': 'Educacion',
                'verbose_name_plural': 'Estudios Registrados',
            },
        ),
    ]
